# This configuration requires 4 gpus with 12GB memory
accum-grad: 4
adim: 512
aheads: 1
backend: pytorch
batch-bins: 1500000
dlayers: 4
dropout-rate: 0.1
dunits: 512
elayers: 12
epochs: 120
eunits: 1536
grad-clip: 5
lsm-weight: 0.1
model-module: espnet.nets.pytorch_backend.e2e_sid_transformer:E2E
mtlalpha: 0.0
opt: noam
patience: 0
sortagrad: 0
transformer-attn-dropout-rate: 0.0
transformer-init: pytorch
transformer-input-layer: conv2d
transformer-length-normalized-loss: false
transformer-lr: 10.0
transformer-warmup-steps: 25000
